services:
  db:
    image: postgres:14  # Use the local postgres image with tag 14
    environment:
      - POSTGRES_DB=postgres3
      - POSTGRES_USER=postgres3
      - POSTGRES_PASSWORD=postgres3
    ports:
      - "5432:5432"  # Expose port for PostgreSQL

  web:
    image: nas415/vlc_maker:latest  # Use the local vlc_maker image
    command: >
      sh -c "
        python3.10 manage.py makemigrations &&
        python3.10 manage.py migrate &&
        python3.10 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app  # Mount current directory to /code in the container
    ports:
      - "8000:8000"  # Expose port for your web service
    depends_on:
      - db

