services:
  web:
    image: nas415/vlc_maker:latest  # Use the local vlc_maker image
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
    command: >
      sh -c "
        python3.10 manage.py makemigrations &&
        python3.10 manage.py migrate &&
        python3.10 manage.py collectstatic --noinput &&
        python3.10 manage.py migrate djstripe &&
        python3.10 manage.py djstripe_sync_models price Invoice Subscription &&
        python3.10 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app  # Mount current directory to /code in the container
    ports:
      - "8000:8000"  # Expose port for your web service
