# Generated by Django 4.2.16 on 2024-09-07 11:39

from django.db import migrations, models
import mainapps.vidoe_text.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_file', models.FileField(upload_to=mainapps.vidoe_text.models.text_file_upload_path)),
                ('voice_id', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('resolution', models.CharField(default='1:1', max_length=50)),
                ('font_file', models.FileField(blank=True, null=True, upload_to=mainapps.vidoe_text.models.font_file_upload_path)),
                ('font_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('subtitle_box_color', models.CharField(default='#000000', max_length=7)),
                ('font_size', models.IntegerField(default=24)),
                ('processed', models.BooleanField(default=False, editable=False)),
            ],
        ),
    ]
