# Generated by Django 4.2.16 on 2024-09-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='subtitle_box_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True),
        ),
    ]
