# Generated by Django 4.2.16 on 2024-09-08 00:53

from django.db import migrations, models
import django.db.models.deletion
import mainapps.vidoe_text.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_videoclip_is_favorite_videoclip_user_delete_userclip'),
        ('vidoe_text', '0003_audioclip_remove_textfile_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlinevideoclip',
            name='video_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage', to='video.videoclip'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=mainapps.vidoe_text.models.font_file_upload_path),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='text_file',
            field=models.FileField(upload_to=mainapps.vidoe_text.models.text_file_upload_path),
        ),
    ]
