# Generated by Django 4.2.16 on 2024-09-08 16:33

from django.db import migrations, models
import mainapps.vidoe_text.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0005_alter_textlinevideoclip_video_file_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textlinevideoclip',
            options={'ordering': ['line_number', 'text_file']},
        ),
        migrations.AddField(
            model_name='textfile',
            name='blank_video',
            field=models.FileField(blank=True, null=True, upload_to='blank_video/'),
        ),
        migrations.AddField(
            model_name='textfile',
            name='fps',
            field=models.IntegerField(default=30, editable=False),
        ),
        migrations.AddField(
            model_name='textfile',
            name='srt_file',
            field=models.FileField(blank=True, null=True, upload_to='srt_files/'),
        ),
        migrations.AddField(
            model_name='textfile',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=mainapps.vidoe_text.models.audio_file_upload_path),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='font_file',
            field=models.FileField(blank=True, null=True, upload_to=mainapps.vidoe_text.models.font_file_upload_path),
        ),
        migrations.AlterUniqueTogether(
            name='textlinevideoclip',
            unique_together={('text_file', 'line_number')},
        ),
    ]
