# Generated by Django 4.2.16 on 2024-09-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0006_alter_textlinevideoclip_options_textfile_blank_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textlinevideoclip',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='textlinevideoclip',
            unique_together=set(),
        ),
    ]
