# Generated by Django 4.2.16 on 2024-09-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0007_alter_textlinevideoclip_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textlinevideoclip',
            options={'ordering': ['line_number', 'text_file']},
        ),
        migrations.AlterUniqueTogether(
            name='textlinevideoclip',
            unique_together={('text_file', 'line_number')},
        ),
    ]
