# Generated by Django 4.2.16 on 2024-09-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0008_alter_textlinevideoclip_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfile',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files'),
        ),
    ]
