# Generated by Django 4.2.16 on 2024-09-10 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vidoe_text', '0009_alter_textfile_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('music_file', models.FileField(upload_to='background_music/')),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('end_time', models.FloatField(help_text='End time in seconds')),
                ('text_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_musics', to='vidoe_text.textfile')),
            ],
        ),
    ]
