# Generated by Django 4.2.16 on 2024-09-10 09:39

from django.db import migrations, models
import mainapps.audio.models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundmusic',
            name='music_file',
            field=models.FileField(upload_to=mainapps.audio.models.bg_music_file_upload_path),
        ),
    ]
