# Generated by Django 4.2.16 on 2024-09-08 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0002_clipcategory_videoclip_userclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclip',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_clips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserClip',
        ),
    ]
