# Generated by Django 4.2.13 on 2024-09-20 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_videoclip_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='video.clipcategory'),
        ),
        migrations.AddConstraint(
            model_name='clipcategory',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_category_per_user'),
        ),
    ]
